# Generated by Django 2.1.5 on 2019-02-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlocked', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_story', models.TextField()),
                ('question_level', models.IntegerField(default=-1)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
