# Generated by Django 2.1.5 on 2019-02-27 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number should be of 10 digits.', regex='^[1-9]\\d{9}$')]),
        ),
    ]
