# Generated by Django 2.1.5 on 2019-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20190227_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='college_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
